/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/api/api`; params?: Router.UnknownInputParams; } | { pathname: `/components/Navbar`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/BalanceList`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/ExpenseList`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/ExpenseModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/GroupHeader`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/GroupTabs`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/InviteModal`; params?: Router.UnknownInputParams; } | { pathname: `/group/GroupDetailScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AddExpenseScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/ExpensesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/SavingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/styles/GlobalStyles`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/api/api`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Navbar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/group/BalanceList`; params?: Router.UnknownOutputParams; } | { pathname: `/components/group/ExpenseList`; params?: Router.UnknownOutputParams; } | { pathname: `/components/group/ExpenseModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/group/GroupHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/components/group/GroupTabs`; params?: Router.UnknownOutputParams; } | { pathname: `/components/group/InviteModal`; params?: Router.UnknownOutputParams; } | { pathname: `/group/GroupDetailScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AddExpenseScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/RegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/tabs/ExpensesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/tabs/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/tabs/SavingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/GlobalStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/api/api${`?${string}` | `#${string}` | ''}` | `/components/Navbar${`?${string}` | `#${string}` | ''}` | `/components/group/BalanceList${`?${string}` | `#${string}` | ''}` | `/components/group/ExpenseList${`?${string}` | `#${string}` | ''}` | `/components/group/ExpenseModal${`?${string}` | `#${string}` | ''}` | `/components/group/GroupHeader${`?${string}` | `#${string}` | ''}` | `/components/group/GroupTabs${`?${string}` | `#${string}` | ''}` | `/components/group/InviteModal${`?${string}` | `#${string}` | ''}` | `/group/GroupDetailScreen${`?${string}` | `#${string}` | ''}` | `/screens/AddExpenseScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/RegisterScreen${`?${string}` | `#${string}` | ''}` | `/screens/tabs/ExpensesScreen${`?${string}` | `#${string}` | ''}` | `/screens/tabs${`?${string}` | `#${string}` | ''}` | `/screens/tabs/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/screens/tabs/SavingsScreen${`?${string}` | `#${string}` | ''}` | `/styles/GlobalStyles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/api/api`; params?: Router.UnknownInputParams; } | { pathname: `/components/Navbar`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/BalanceList`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/ExpenseList`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/ExpenseModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/GroupHeader`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/GroupTabs`; params?: Router.UnknownInputParams; } | { pathname: `/components/group/InviteModal`; params?: Router.UnknownInputParams; } | { pathname: `/group/GroupDetailScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AddExpenseScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/ExpensesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/SavingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/styles/GlobalStyles`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
